In [1]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
df=pd.read_csv('diabetes.csv')
df.head(10)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   
5            5      116             74              0        0  25.6   
6            3       78             50             32       88  31.0   
7           10      115              0              0        0  35.3   
8            2      197             70             45      543  30.5   
9            8      125             96              0        0   0.0   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1  
5                     0.201   30        0  
6                     0.248   26        1  
7                     0.134   29        0  
8                     0.158   53        1  
9                     0.232   54        1

In [2]:
df.shape

(768, 9)

In [3]:
import numpy as np

In [4]:
df['Glucose'] = np.where(df['Glucose']==0,df['Glucose'].median(),df['Glucose'])
df["Insulin"] = np.where(df["Insulin"]==0, df["Insulin"].median(), df["Insulin"])
df["SkinThickness"] = np.where(df["SkinThickness"]==0, df["SkinThickness"].median(), df["SkinThickness"])

In [5]:
df.head(10)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6    148.0             72           35.0     30.5  33.6   
1            1     85.0             66           29.0     30.5  26.6   
2            8    183.0             64           23.0     30.5  23.3   
3            1     89.0             66           23.0     94.0  28.1   
4            0    137.0             40           35.0    168.0  43.1   
5            5    116.0             74           23.0     30.5  25.6   
6            3     78.0             50           32.0     88.0  31.0   
7           10    115.0              0           23.0     30.5  35.3   
8            2    197.0             70           45.0    543.0  30.5   
9            8    125.0             96           23.0     30.5   0.0   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1  
5                     0.201   30        0  
6                     0.248   26        1  
7                     0.134   29        0  
8                     0.158   53        1  
9                     0.232   54        1

In [6]:
### Independent and Dependent features
X = df.drop("Outcome",axis=1)
y = df["Outcome"]

In [7]:
X

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6    148.0             72           35.0     30.5  33.6   
1              1     85.0             66           29.0     30.5  26.6   
2              8    183.0             64           23.0     30.5  23.3   
3              1     89.0             66           23.0     94.0  28.1   
4              0    137.0             40           35.0    168.0  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10    101.0             76           48.0    180.0  32.9   
764            2    122.0             70           27.0     30.5  36.8   
765            5    121.0             72           23.0    112.0  26.2   
766            1    126.0             60           23.0     30.5  30.1   
767            1     93.0             70           31.0     30.5  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [18]:
from sklearn.ensemble import RandomForestClassifier
rf_classifier = RandomForestClassifier(n_estimators=20).fit(X_train, y_train)
prediction = rf_classifier.predict(X_test)

In [19]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print(confusion_matrix(y_test,prediction))
print(accuracy_score(y_test,prediction))
print(classification_report(y_test,prediction))

[[95 12]
 [20 27]]
0.7922077922077922
              precision    recall  f1-score   support

           0       0.83      0.89      0.86       107
           1       0.69      0.57      0.63        47

    accuracy                           0.79       154
   macro avg       0.76      0.73      0.74       154
weighted avg       0.79      0.79      0.79       154



In [20]:
### Parameters
from sklearn.model_selection import RandomizedSearchCV
n_estimators  = [int(x) for x in np.linspace(start=10,stop=2500,num=10)]

max_features = ["auto", "sqrt", "log2"]

max_depth = [int(x) for x in np.linspace(10,1500,10)]

min_samples_split = [2,7,9,14]

min_samples_leaf = [1,2,5,6,8]

In [21]:
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
              'criterion':['entropy','gini']}

print(random_grid)

{'n_estimators': [10, 286, 563, 840, 1116, 1393, 1670, 1946, 2223, 2500], 'max_features': ['auto', 'sqrt', 'log2'], 'max_depth': [10, 175, 341, 506, 672, 837, 1003, 1168, 1334, 1500], 'min_samples_split': [2, 7, 9, 14], 'min_samples_leaf': [1, 2, 5, 6, 8], 'criterion': ['entropy', 'gini']}


In [22]:
rf = RandomForestClassifier()
rf_randomcv=RandomizedSearchCV(estimator=rf, param_distributions=random_grid,cv=3,n_iter=10,n_jobs=-1,random_state=100,verbose=2)

rf_randomcv.fit(X_train,y_train)

Fitting 3 folds for each of 10 candidates, totalling 30 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  30 out of  30 | elapsed:   54.7s finished


RandomizedSearchCV(cv=3, estimator=RandomForestClassifier(), n_jobs=-1,
                   param_distributions={'criterion': ['entropy', 'gini'],
                                        'max_depth': [10, 175, 341, 506, 672,
                                                      837, 1003, 1168, 1334,
                                                      1500],
                                        'max_features': ['auto', 'sqrt',
                                                         'log2'],
                                        'min_samples_leaf': [1, 2, 5, 6, 8],
                                        'min_samples_split': [2, 7, 9, 14],
                                        'n_estimators': [10, 286, 563, 840,
                                                         1116, 1393, 1670, 1946,
                                                         2223, 2500]},
                   random_state=100, verbose=2)

In [23]:
rf_randomcv.best_params_

{'n_estimators': 2500,
 'min_samples_split': 14,
 'min_samples_leaf': 1,
 'max_features': 'sqrt',
 'max_depth': 506,
 'criterion': 'gini'}

In [24]:
rf_randomcv.best_score_

0.7524310537223019

In [25]:
best_random_grid=rf_randomcv.best_estimator_

In [26]:
best_random_grid

RandomForestClassifier(max_depth=506, max_features='sqrt', min_samples_split=14,
                       n_estimators=2500)

In [27]:
y_pred=best_random_grid.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print("Accuracy Score {}".format(accuracy_score(y_test,y_pred)))
print("Classification report: {}".format(classification_report(y_test,y_pred)))

[[96 11]
 [17 30]]
Accuracy Score 0.8181818181818182
Classification report:               precision    recall  f1-score   support

           0       0.85      0.90      0.87       107
           1       0.73      0.64      0.68        47

    accuracy                           0.82       154
   macro avg       0.79      0.77      0.78       154
weighted avg       0.81      0.82      0.81       154



In [28]:
model=RandomForestClassifier(max_depth=1003, max_features='log2', min_samples_leaf=5,n_estimators=563)
model.fit(X_train, y_train)
model.score(X_test,y_test)

0.8441558441558441

In [29]:
from sklearn.model_selection import cross_val_score
# accuracy = cross_val_score(model,X_test, y_test, cv=4)
accuracy=cross_val_score(model, X_train, y_train, cv=10)
print(f"accuracy: {accuracy} \n accuracy mean: {accuracy.mean()}")

accuracy: [0.69354839 0.72580645 0.75806452 0.82258065 0.73770492 0.81967213
 0.68852459 0.68852459 0.78688525 0.78688525] 
 accuracy mean: 0.7508196721311475


In [30]:
pred=model.predict([[0,110,65,23,30,25,0.6,32]])
pred

array([0], dtype=int64)

In [31]:
y_test.head()

661    1
122    0
113    0
14     1
529    0
Name: Outcome, dtype: int64

In [32]:
pred_rf = model.predict(X_test)
for i in range(30):
    print(f"prediction: {pred_rf[i]} actual: {y_test.values[i]}")

prediction: 1 actual: 1
prediction: 0 actual: 0
prediction: 0 actual: 0
prediction: 1 actual: 1
prediction: 0 actual: 0
prediction: 0 actual: 0
prediction: 1 actual: 1
prediction: 1 actual: 1
prediction: 0 actual: 0
prediction: 0 actual: 0
prediction: 1 actual: 1
prediction: 1 actual: 1
prediction: 0 actual: 0
prediction: 0 actual: 0
prediction: 0 actual: 0
prediction: 0 actual: 0
prediction: 1 actual: 1
prediction: 0 actual: 0
prediction: 0 actual: 0
prediction: 0 actual: 0
prediction: 1 actual: 1
prediction: 0 actual: 1
prediction: 0 actual: 0
prediction: 0 actual: 0
prediction: 0 actual: 0
prediction: 0 actual: 0
prediction: 0 actual: 0
prediction: 1 actual: 0
prediction: 0 actual: 0
prediction: 0 actual: 0


In [33]:
model.score(X_train, y_train)

0.9055374592833876

In [42]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, pred_rf)
mse**0.5

0.39477101697586137

In [44]:
import pickle
file = open("diabetes.pkl", "wb")
pickle.dump(model,file)
file.close()

In [47]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [46]:
df.Pregnancies.unique()

array([ 6,  1,  8,  0,  5,  3, 10,  2,  4,  7,  9, 11, 13, 15, 17, 12, 14],
      dtype=int64)

In [56]:
df.Glucose.unique()

array([148.,  85., 183.,  89., 137., 116.,  78., 115., 197., 125., 110.,
       168., 139., 189., 166., 100., 118., 107., 103., 126.,  99., 196.,
       119., 143., 147.,  97., 145., 117., 109., 158.,  88.,  92., 122.,
       138., 102.,  90., 111., 180., 133., 106., 171., 159., 146.,  71.,
       105., 101., 176., 150.,  73., 187.,  84.,  44., 141., 114.,  95.,
       129.,  79.,  62., 131., 112., 113.,  74.,  83., 136.,  80., 123.,
        81., 134., 142., 144.,  93., 163., 151.,  96., 155.,  76., 160.,
       124., 162., 132., 120., 173., 170., 128., 108., 154.,  57., 156.,
       153., 188., 152., 104.,  87.,  75., 179., 130., 194., 181., 135.,
       184., 140., 177., 164.,  91., 165.,  86., 193., 191., 161., 167.,
        77., 182., 157., 178.,  61.,  98., 127.,  82.,  72., 172.,  94.,
       175., 195.,  68., 186., 198., 121.,  67., 174., 199.,  56., 169.,
       149.,  65., 190.])

In [57]:
df.BloodPressure.unique()

array([ 72,  66,  64,  40,  74,  50,   0,  70,  96,  92,  80,  60,  84,
        30,  88,  90,  94,  76,  82,  75,  58,  78,  68, 110,  56,  62,
        85,  86,  48,  44,  65, 108,  55, 122,  54,  52,  98, 104,  95,
        46, 102, 100,  61,  24,  38, 106, 114], dtype=int64)

In [58]:
df.SkinThickness.unique()

array([35., 29., 23., 32., 45., 19., 47., 38., 30., 41., 33., 26., 15.,
       36., 11., 31., 37., 42., 25., 18., 24., 39., 27., 21., 34., 10.,
       60., 13., 20., 22., 28., 54., 40., 51., 56., 14., 17., 50., 44.,
       12., 46., 16.,  7., 52., 43., 48.,  8., 49., 63., 99.])

In [59]:
df.Insulin.unique()

array([ 30.5,  94. , 168. ,  88. , 543. , 846. , 175. , 230. ,  83. ,
        96. , 235. , 146. , 115. , 140. , 110. , 245. ,  54. , 192. ,
       207. ,  70. , 240. ,  82. ,  36. ,  23. , 300. , 342. , 304. ,
       142. , 128. ,  38. , 100. ,  90. , 270. ,  71. , 125. , 176. ,
        48. ,  64. , 228. ,  76. , 220. ,  40. , 152. ,  18. , 135. ,
       495. ,  37. ,  51. ,  99. , 145. , 225. ,  49. ,  50. ,  92. ,
       325. ,  63. , 284. , 119. , 204. , 155. , 485. ,  53. , 114. ,
       105. , 285. , 156. ,  78. , 130. ,  55. ,  58. , 160. , 210. ,
       318. ,  44. , 190. , 280. ,  87. , 271. , 129. , 120. , 478. ,
        56. ,  32. , 744. , 370. ,  45. , 194. , 680. , 402. , 258. ,
       375. , 150. ,  67. ,  57. , 116. , 278. , 122. , 545. ,  75. ,
        74. , 182. , 360. , 215. , 184. ,  42. , 132. , 148. , 180. ,
       205. ,  85. , 231. ,  29. ,  68. ,  52. , 255. , 171. ,  73. ,
       108. ,  43. , 167. , 249. , 293. ,  66. , 465. ,  89. , 158. ,
        84. ,  72. ,

In [60]:
# BMI', 'DiabetesPedigreeFunction
df.BMI.unique()

array([33.6, 26.6, 23.3, 28.1, 43.1, 25.6, 31. , 35.3, 30.5,  0. , 37.6,
       38. , 27.1, 30.1, 25.8, 30. , 45.8, 29.6, 43.3, 34.6, 39.3, 35.4,
       39.8, 29. , 36.6, 31.1, 39.4, 23.2, 22.2, 34.1, 36. , 31.6, 24.8,
       19.9, 27.6, 24. , 33.2, 32.9, 38.2, 37.1, 34. , 40.2, 22.7, 45.4,
       27.4, 42. , 29.7, 28. , 39.1, 19.4, 24.2, 24.4, 33.7, 34.7, 23. ,
       37.7, 46.8, 40.5, 41.5, 25. , 25.4, 32.8, 32.5, 42.7, 19.6, 28.9,
       28.6, 43.4, 35.1, 32. , 24.7, 32.6, 43.2, 22.4, 29.3, 24.6, 48.8,
       32.4, 38.5, 26.5, 19.1, 46.7, 23.8, 33.9, 20.4, 28.7, 49.7, 39. ,
       26.1, 22.5, 39.6, 29.5, 34.3, 37.4, 33.3, 31.2, 28.2, 53.2, 34.2,
       26.8, 55. , 42.9, 34.5, 27.9, 38.3, 21.1, 33.8, 30.8, 36.9, 39.5,
       27.3, 21.9, 40.6, 47.9, 50. , 25.2, 40.9, 37.2, 44.2, 29.9, 31.9,
       28.4, 43.5, 32.7, 67.1, 45. , 34.9, 27.7, 35.9, 22.6, 33.1, 30.4,
       52.3, 24.3, 22.9, 34.8, 30.9, 40.1, 23.9, 37.5, 35.5, 42.8, 42.6,
       41.8, 35.8, 37.8, 28.8, 23.6, 35.7, 36.7, 45

In [61]:
df.DiabetesPedigreeFunction.unique()

array([0.627, 0.351, 0.672, 0.167, 2.288, 0.201, 0.248, 0.134, 0.158,
       0.232, 0.191, 0.537, 1.441, 0.398, 0.587, 0.484, 0.551, 0.254,
       0.183, 0.529, 0.704, 0.388, 0.451, 0.263, 0.205, 0.257, 0.487,
       0.245, 0.337, 0.546, 0.851, 0.267, 0.188, 0.512, 0.966, 0.42 ,
       0.665, 0.503, 1.39 , 0.271, 0.696, 0.235, 0.721, 0.294, 1.893,
       0.564, 0.586, 0.344, 0.305, 0.491, 0.526, 0.342, 0.467, 0.718,
       0.962, 1.781, 0.173, 0.304, 0.27 , 0.699, 0.258, 0.203, 0.855,
       0.845, 0.334, 0.189, 0.867, 0.411, 0.583, 0.231, 0.396, 0.14 ,
       0.391, 0.37 , 0.307, 0.102, 0.767, 0.237, 0.227, 0.698, 0.178,
       0.324, 0.153, 0.165, 0.443, 0.261, 0.277, 0.761, 0.255, 0.13 ,
       0.323, 0.356, 0.325, 1.222, 0.179, 0.262, 0.283, 0.93 , 0.801,
       0.207, 0.287, 0.336, 0.247, 0.199, 0.543, 0.192, 0.588, 0.539,
       0.22 , 0.654, 0.223, 0.759, 0.26 , 0.404, 0.186, 0.278, 0.496,
       0.452, 0.403, 0.741, 0.361, 1.114, 0.457, 0.647, 0.088, 0.597,
       0.532, 0.703,

In [62]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  121.656250      69.105469      27.334635   94.652344   
std       3.369578   30.438286      19.355807       9.229014  105.547598   
min       0.000000   44.000000       0.000000       7.000000   14.000000   
25%       1.000000   99.750000      62.000000      23.000000   30.500000   
50%       3.000000  117.000000      72.000000      23.000000   31.250000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [65]:
corr_matt = df.corr()
corr_matt["Outcome"].sort_values(ascending=False)

Outcome                     1.000000
Glucose                     0.492782
BMI                         0.292695
Age                         0.238356
Pregnancies                 0.221898
SkinThickness               0.189065
DiabetesPedigreeFunction    0.173844
Insulin                     0.148457
BloodPressure               0.065068
Name: Outcome, dtype: float64